Repository lo-cafe/winston, pull requests merged in 2023-09, with the labels that each got.

#40 add infinite scrolling to user profiles
  winston/models/RedditAPI/user/fetchUserOverview.swift
  winston/models/User.swift
  winston/views/UserView.swift
Labels: feature/enhancement

#36 fix duplicate posts showing up in the feed
  winston/components/Media/mediaExtractor.swift
  winston/views/SubredditPosts.swift
Labels: bug

#16 Button to scroll to next root level comment
  winston/components/PostFloatingPill.swift
  winston/views/PostView/PostReplies.swift
  winston/views/PostView/PostView.swift
Labels: feature/enhancement

#35 Add Live Text to Images
  winston.xcodeproj/project.pbxproj
  winston.xcodeproj/xcuserdata/daniel.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  winston/components/LightBoxImage/LightBoxElementView.swift
  winston/components/LightBoxImage/LightBoxImage.swift
  winston/components/LightBoxImage/LightBoxOverlay.swift
  winston/components/LightBoxImage/ZoomableImageView.swift
  winston/components/LiveTextInteraction.swift
  winston/components/Media/ImageMediaPost.swift
  winston/components/ShareSheet.swift
  winston/components/URLImage.swift
  winston/globals/defaults.swift
  winston/modifiers/PinchToZoom.swift
  winston/utils/saveMedia.swift
  winston/views/Settings/views/GeneralPanel.swift
Labels: feature/enhancement

#37 Paginated feed and graphic for when a user reaches the end of a feed
  winston/Assets.xcassets/winstonEndOfFeed.imageset/winston fossils transparent.png
  winston/globals/defaults.swift
  winston/views/Settings/views/BehaviorPanel.swift
  winston/views/SubredditPosts.swift
Labels: feature/enhancement

#42 Next parent comment stuck experimental fix
  winston/views/PostView/PostReplies.swift
Labels: bug/fix

#55 Fixed duplicate share button
  winston/components/Links/PostLink.swift
Labels: bug/fix

#33 Update Subreddit in README.md
  README.md
Labels: documentation, question

#49 Add top sort timeframe options and make searching subreddits fully functional
  winston/models/RedditAPI/subs/fetchSubPosts.swift
  winston/models/Subreddit.swift
  winston/views/Search.swift
  winston/views/Settings/views/BehaviorPanel.swift
  winston/views/SubredditPosts.swift
Labels: feature/enhancement

#59 Subreddit and user hyperlink
  winston/components/Markdownosaur.swift
Labels: feature/enhancement

#38 Open Links in WebView instead of Safari
  winston.xcodeproj/project.pbxproj
  winston.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  winston.xcodeproj/xcuserdata/daniel.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  winston/Tabber.swift
  winston/components/HandleDeepLinks.swift
  winston/components/Links/CommentLink/CommentLinkContent.swift
  winston/components/MD2.swift
  winston/components/Markdownosaur.swift
  winston/components/Media/MediaPresenter.swift
  winston/components/Media/PreviewLink/PreviewLinkContent.swift
  winston/utils/redditURLParser.swift
  winston/utils/webView.swift
  winston/views/PostView/PostContent.swift
  winston/views/SubredditInfo/SubredditRulesTab.swift
Labels: feature/enhancement

#73 Add tasks to upvote / downvote for comments
  winston/components/Links/CommentLink/CommentLinkContent.swift
Labels: feature/enhancement

#72 add support for filtering subreddits
  winston/globals/defaults.swift
  winston/models/Post.swift
  winston/models/SwipeAction.swift
  winston/views/Settings/Settings.swift
  winston/views/Settings/subSettingView/FilteredSubredditsSettings.swift
  winston/views/Settings/views/BehaviorPanel.swift
  winston/views/SubredditPosts.swift
Labels: feature/enhancement
